spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost/mysql
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


#mybatis.config：mybatis-config.xml配置文件的路径
#mybatis.typeHandlersPackage：扫描typeHandlers的包
#mybatis.checkConfigLocation：检查配置文件是否存在
#mybatis.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model
